# Generated by Django 4.2.1 on 2023-05-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_favorite_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
