# Generated by Django 4.2.1 on 2023-05-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_follow_unique_follow_follow_unique_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
    ]
